### ISSUE TITLE
Allow optional skipping of outputChildsType

### ISSUE THREAD

**Issue by ijongkim** [gmfmi/searchinGhost#2]
Per feedback from this Ghost forum thread: https://forum.ghost.org/t/searchinghost-the-new-search-plugin-competitor/13971/25

I would like to propose that we allow an option to skip the wrapping of search results as it can be unnecessary at best and break existing site styles at worst.

Requirements:
- Use value of `false` to indicate skipping of child wrappers
- Handle empty template case
- Handle results found template case

**Comment by ijongkim** [comment]
Currently `template` and `emptyTemplate` functions return strings which are then set as the wrapper element's inner HTML. Due to this existing pattern, I had suggested we insert the returned value of the template functions using `insertAdjacentHTML`.

However, upon a second thought, I realized the template functions could also return proper Elements and those could be appended using `appendChild`.

The benefit of the first approach is that users won't have to refactor their `template` or `emptyTemplate` functions to take advantage of this option.

The benefit of the second approach is that it requires only a single check in `evaluateTemplate()` and the rest of your code in `display()` can remain as is.

Do you have any opinions on which approach you'd prefer?

**Comment by gmfmi** [comment]
From my perspective, we cannot ask the users to refactor `template` and `emptyTemplate` without releasing a major version as we will introduce API breaking changes. Plus, the simpler the better for the users so I think dead-simple HTML template is best.

My first thoughts:

- update `evaluateTemplate` to return an HTML element OR an HTML string depending on the value of `outputChildsType`
- create a new method to insert the result based on its type that looks like (I did not try so I don't know which `typeof` must be matched):
```js
insertGeneratedHTML(generatedTemplate) {
    if (generatedTemplate) {
        if (typeof generatedTemplate === HTMLElement) {
            resultParentElement.appendChild(generatedTemplate);
        } else {
            resultParentElement.innerHTML = generatedTemplate;
        }
    }
}
```
- Then, call this method from `display`:
```js
let htmlResult = this.evaluateTemplate(this.config.emptyTemplate, null);
this.insertGeneratedHTML(htmlResult);
// and
let htmlResult = this.evaluateTemplate(this.config.template, post);
this.insertGeneratedHTML(htmlResult);
```

I think with this way the code remains consistent but of course if you come up with a better idea, go on! :)
