### ISSUE TITLE
Question on showing no posts found msg

### ISSUE THREAD

**Issue by hiensarahly** [gmfmi/searchinGhost#4]
Hi, I’m trying to implement the method to show latest posts when nothing is found in search. But I am a bit stuck to find where we can add a nothing-found msg on top of the results.

emptyTemplate: function() {
    /* for example, displaying ‘sorry, nothing found’ message here*/
    var allPostsArray = Object.values(searchinGhost.index.l);
    var latestPosts = allPostsArray.slice(0, 6);
    searchinGhost.display(latestPosts);
}

Do you have any suggestions or pointers for this? Thank you.

**Comment by gmfmi** [comment]
Hi @hiensarahly,

I think it is possible but difficult to do it within the 'emptyTemplate' function. Basically, this function has been designed to display something that totally **replaces** all the posts.

The best way to achive that is to use the hook function "onSearchEnd()". I am going to test it right now and I will give you back the answer when I get a fully working example!

**Comment by gmfmi** [comment]
Here is what you can do:

1. In your theme, add an HTML element hidden by default to display when nothing is found
```html
<p id="empty-message" style="visibility:hidden;">Wooops, nothing found for your search</p>
```

2. Add this extra configuration in your searchinGhost settings
```js
new SearchinGhost({
    key: '...',
    url: '...',
    [...]
    emptyTemplate: function() {
        var allPostsArray = Object.values(searchinGhost.index.l);
        var latestPosts = allPostsArray.slice(0, 3);
        searchinGhost.display(latestPosts);
    },
    onSearchEnd: function(posts) {
        var query = document.getElementById('search-bar').value.toLowerCase();
        var emptyMsgElement = document.getElementById('empty-message');
        if (posts.length < 1 && query != '') {
            emptyMsgElement.style.visibility = 'visible'
        } else {
            emptyMsgElement.style.visibility = 'hidden';
        }
    }
});
```

I quickly tested out and it works like a charm 😃  Also, if you want to do it a little bit "cleaner", you might want to add/remove a CSS class instead of using the "visibility" property.

Let me know if it works for you!

**Comment by hiensarahly** [comment]
Hooray! It's alive it's working. Thank you for your elegant search bar. It took me a while to figure out a good placement for this part: 

`<p id="empty-message" style="visibility:hidden;">Wooops, nothing found for your search</p>`

So it doesn't hide or collide with other elements on the page.

After that I realized I could put it outside of the search wrapper! May I send you a screenshot via the Ghost Forum? 

I am very glad. Thanks @gmfmi !!

**Comment by gmfmi** [comment]
Great! Happy to read that :)

Yes of course, send me a screenshot if you website is offline or directly a link to an online version so I can test it live (and make a code review if you want to?).
