### ISSUE TITLE
[ALREADY DONE] Vue.js/Nuxt.js compatibility

### ISSUE THREAD

**Issue by ajacquierbret** [gmfmi/searchinGhost#5]
Hi @gmfmi and everyone else who reads this ! First, huge thanks for your work on this lib, it's literally the easiest to implement search bar I've tested, and it uses the most fast and accurate search engine I've tested too.

Though I had some troubles using searchInGhost with Nuxt.js framework in the beginning, I found a temporary workaround. In fact it's basically just a few tweaks inside the main file so that some errors are now warnings and most important functions can now return search results which can be pulled from the main class instanciation located in your app's source code.

Because we now have a direct access to search results, instead of being handled in our back with vanilla JS DOM manipulations, we can very easily integrate it in any Vue/Nuxt templating system. I personnaly use Vuetify's `v-text-field` component and some dead simple `v-list` component to display search results, what was impossible before because of Vue's virtual DOM.

If someone cares, just tell me and I'll be happy to create a fork of this repo with my modifications, or even to create a Nuxt plugin based on this lib.

A little preview of my implementation of the library : 

<img width="928" alt="Capture d’écran 2020-07-04 à 17 11 19" src="https://user-images.githubusercontent.com/45269819/86515499-87cc6280-be19-11ea-8a87-49c12f252c2c.png">

Script :

```javascript
// Navbar.vue
data: () => ({
    search: false,
    searchQuery: '',
    foundPosts: [],
    searchinGhost: {}
  }),
mounted() {
    this.searchinGhost = new SearchinGhost({
      url: GHOST_API_URL,
      key: CONTENT_API_KEY,
      mode: 'vue',
      vueWarns: true
    })
  },
methods: {
    fillFoundPosts() {
      this.foundPosts = this.searchinGhost.search(this.searchQuery)
    }
  }
```

Template :

```html
// Navbar.vue
<v-menu offset-y rounded transition="slide-y-transition" :fixed="false">
      <template v-slot:activator="{ on }">
        <v-text-field
          id="search-bar"
          v-model="searchQuery"
          item-text="title"
          item-value="excerpt"
          type="search"
          @keyup="fillFoundPosts"
          v-on="on"
        ></v-text-field>
      </template>
      <v-list
        v-show="searchQuery.charAt(0) !== '' || undefined || null"
        transition="slide-y-transition"
      >
        <v-list-item
          v-for="post in foundPosts"
          :key="post.id"
        >
          <v-list-item-avatar>
            <v-img :src="post ? post.feature_image : null"></v-img>
          </v-list-item-avatar>
          <v-list-item-content>
            <v-list-item-title>{{ post ? post.title : '' }}</v-list-item-title>
            <v-list-item-subtitle>{{
              post ? post.published_at : ''
            }}</v-list-item-subtitle>
            <v-list-item-text>{{ post ? post.excerpt : '' }}</v-list-item-text>
          </v-list-item-content>
        </v-list-item>
      </v-list>
    </v-menu>
```

Library (**SHOWING ONLY MODIFICATIONS AND NEW THINGS**) : 

```javascript
// ./utils/searchinghost.js (I moved the main file out of node_modules)
this.config = {
      // Two new options are provided here
      mode: 'default',
      vueWarns: false,

      ...

}

...

// Here we turn errors into warnings if "mode: 'vue'" setting is enabled
    if (!this.searchBar && !this.config.inputId) {
      this.searchBar = document.createElement('input')
    }
    if (!this.searchBar && this.config.mode === 'default') {
      throw `Unable to find the input element #${this.config.inputId}, please check your configuration`
    } else if (
      !this.searchBar &&
      this.config.mode === 'vue' &&
      this.config.vueWarns
    ) {
      console.warn(
        `[Vue mode] : Unable to find the input element #${this.config.inputId}, please check your configuration`
      )
    }
if (this.config.mode === 'default') {

    ...

    if (!this.searchResultElement && this.config.mode === 'default') {
      throw `Unable to find the output element #${this.config.outputId}, please check your configuration`
    } else if (
      !this.searchResultElement &&
      this.config.mode === 'vue' &&
      this.config.vueWarns
    ) {
      console.warn(
        `[Vue mode] : Unable to find the output element #${this.config.outputId}, please check your configuration`
      )
    }

search(inputQuery) {

    ...

     // Here we prevent DOM manipulations from displaying search results
    if (this.config.mode === 'default') {
      this.display(postsFound)
    }

    ...

    // Here we just add a return statement so that the result can be passed to our class instance
    return postsFound
  }
```

**Comment by gmfmi** [comment]
Hi @ajacquierbret, thank you for the kind words 😃 

After reading your comment, I think it could be helpful for other people using any JS framework. I will release a new version that embed the updates in 1 or 2 days. I will implement it differently by allowing the `"outputId` to be optional when setting its value to `false` (just like `"inputId"`). This way, your configuration will look like:

```js
var searchinGhost = new SearchinGhost({
    key: '<CONTENT_API_KEY>',
    inputId: false,
    outputId: false,
    [...]
});
```

About the `throw ...` issue, I will convert them into `console.warn()`. I did not know it could cause trouble when used by someone else.

Also, pure curiosity, how did you discover SearchinGhost? Through the Ghost forum?

**Comment by gmfmi** [comment]
Well, finally, the release (v1.4.0 - e96fdb3) made its way faster than expected. Feel free to test it out and give me some feedback 😉

**Comment by gmfmi** [comment]
@ajacquierbret, any hint on that Nuxt.js related issue ? [issue #8](https://github.com/gmfmi/searchinGhost/issues/8)

**Comment by ajacquierbret** [comment]
Hi @gmfmi ! Sorry for my late answer, I've been quite busy last weeks. I don't remember if I had enough time to test your release, but if not I'll do it soon ! Will try to answer issue #8 these days.
