### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by tychotycho** [gmfmi/searchinGhost#8]
Getting this error in a Nuxt 'npm run dev' as well as 'npm run generate' static build:

node_modules/searchinghost/src/searchinghost.js:1

```
(function (exports, require, module, __filename, __dirname) { import FlexSearch from 'flexsearch';
                                                              ^^^^^^
SyntaxError: Cannot use import statement outside a module
```

Using the exact example that **ajacquierbret** suggested:

```
import SearchinGhost from 'searchinghost'
export default {
  components: {
    Logo,
    mobileNav
  },
  data () {
    return {
      search: false,
      searchQuery: '',
      foundPosts: [],
      searchinGhost: {},
      isOpen: false,
      isOpenMobile: false,
      isSearch: false
    }
  },
  mounted () {
    this.searchinGhost = new SearchinGhost({
      key: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
      inputId: false,
      outputId: false
    })
  },
  methods: {
    fillFoundPosts () {
      this.foundPosts = this.searchinGhost.search(this.searchQuery)
    }
  }
}

```

Any help greatly appreciated.

**Comment by gmfmi** [comment]
Hi @tychotycho, unfortunately I never used Nuxt so I won't be able to properly help you on that one. It really seems weird to get an error on an import within SearchinGhost...

**Comment by gmfmi** [comment]
The issue seems to be more related to your implementation than the product itself so I am closing it for now. If needed, feel free to reopen this issue.
